<?php
$DeleteFunctions = [["all","Deletes all sectors table"],["id","delete all that matches id in sectors"]];
$delete = ["all","id"];
$login = ["sectorsName","moreUsed","PASSWORD_BCRYPT"];
$columnasSQL = [["id","INT","11","",false,true,"autoincremental | 1 unique id for each sector",true],["sectorsName","VARCHAR","32","",true,false,"Sectors being offered (gastronomics, cloth, etc)",false],["moreUsed","INT","32","0",true,false,"How many times where used (for statistics)",false]];
$DBUSER = "DBUSER";
$post = [["set","all","","Insert a new row in sectors",",",""],["delete","all","","delete all table in sectors","",""],["delete","","id","delete all that matches id in sectors","","id"],["delete","","sectorsName","delete all that matches sectorsName in sectors","","sectorsName"],["delete","","moreUsed","delete all that matches moreUsed in sectors","","moreUsed"],["update","all","id","Updates all that matches id in sectors","","id"],["update","all","sectorsName","Updates all that matches sectorsName in sectors","","sectorsName"],["update","all","moreUsed","Updates all that matches moreUsed in sectors","","moreUsed"],["update","sectorsName","id","Updates sectorsName that matches id in sectors","","sectorsName,id"],["update","sectorsName","moreUsed","Updates sectorsName that matches moreUsed in sectors","","sectorsName,moreUsed"],["update","moreUsed","id","Updates moreUsed that matches id in sectors","","moreUsed,id"],["update","moreUsed","sectorsName","Updates moreUsed that matches sectorsName in sectors","","moreUsed,sectorsName"]];
$destination = "api/v1/sectors";
$DBNAME = "DBNAME";
$claves = ["-----BEGIN RSA PRIVATE KEY-----\r\nMIIEpAIBAAKCAQEA175CYeb6MI+T69dw1cxxif9LOEDACRPvV5X0fpjKOZ6vNqXi\r\nbYy4Vy1gKu/pVIc/f1osrL2/MH2xR7UebUZMbip8jGwqubgvpiVogNA6ACt3iVRQ\r\ng7S4/XCCzU4hN/ZPK04JkF7dIRPvBOjMGDrYVCm9stu8KrWC9dbcuY94QRowePiO\r\nIcjjtKCOE6ErfhEJE1fp7qimEX9GGMsmzHnuwZtbnw1GeRCMrCQ5Jq8Xc79dOwq6\r\nauNqUTSITG8mD5b/nk6Ogvnn/pNXmxFEroC5V4AdXNw1BvOhJLM85p1SN6zxn0Wb\r\n7KTWVfZmzKJEp7nAPZ1UJFKiWNIdLpVed6xHHwIDAQABAoIBAQC4+hEynfb/sesT\r\nODovpcXnmvNkfOfqIKSDBTiHXvtsoej6wwo8AX6AiJA+4Eq/xeKkj61kQqBttCdP\r\nIzS+XprjjhwRziBn8kswejx6zY4dXSd1oMwT0N0Xt+L+orGKqO5CY/uBRET2un+i\r\nRvPPBo06xDs44nwYZl6t6BaCJ0flEDszPextbIw1bbWXfmrOiAXbfyibKe/Sccos\r\nNgMiLIKbXtAoNCl3Qf4D0SD+n/8BzmR8aj5xeyNy6JseQffv8xV64hemjxdPc17x\r\nDPhUYrH2UbbnmU2244/LrL8SIXf+lo8qwZXxqiWcZRR7qZ25BHXN0fuJDTFTlsM7\r\nLSs3oVZxAoGBAPJxBlagmq6sME51NRdO3qSCRC/2CZl+DFjkhBsp4Iegq20ts1WJ\r\nDeuY3Oh2lNu4MOBvqKlbm/gZq7XSl8G6/MlWMyzPMCEmavoBcWGR2JCsTehIjxWK\r\nSzQ7h6WXyPHZsDqdex1N3FKEin0U5idS1A5355RIURpOKaRJYDNXiGzZAoGBAOPP\r\nAGRGFORJ/li8Cjw1RUegFYaK9o3dpwi2cWi6txXhJMzUUBtDr6t1hD3xCHZlKn5U\r\npzwcCsMURrPR6lpGqB6ErxvGiW87bWrelmQVP7aoU8+BGqRudeNtOY5Wg07wyyuy\r\nEGWhSwthcZg+9AN6hy7tBhFzX0IM7TCGetStrzi3AoGAI+XocltFjCei33sraVAc\r\nV2+SeSeNNFUdruvnQ75nqK15tKjXrQqmLQRtcV5dnEshsZnW93zBE3N5oWqVXfI6\r\nC/Xfjfr/vWja3jnod/IIhyN8RbC4vw/DIvDNnQ9kiasaFRPMbwJgZTeK6gp2Kcxx\r\n6dKHT8WFfMemEtVqkS+c28ECgYEAhayZ1j0pVSv2C6uLdfjsRjMxbllsg6JkuUAV\r\nHBc0B6qtJWQP/W+iTUIP7yjYhmCmpqqV1ze9OOtU8X9jvMVpMT86YVoGmzaL5gHm\r\nzaOKV2w+gayILaSDmIgnFda+BjxVe7Zo2LnkhzEOrv+Bv+jOGkMLJIJGi0N6itbe\r\njJ2+C9ECgYA/yX/22TNVO7XcO3RJBMTtmicgOZ7bGNdxCzoogL9mEiARBh79scEm\r\np8dSp0O3Lcwa99a8paNGl3mefi45iLlFnwpKJHs7QolU3CvNbZh8aohTOpr55Pgw\r\nBa9nUTpKAiXQLku4ETZ0R0xzJvPymyVnTf/4lzjV3QqNYikf0ZVW1A==\r\n-----END RSA PRIVATE KEY-----\r\n","-----BEGIN PUBLIC KEY-----\r\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA175CYeb6MI+T69dw1cxx\r\nif9LOEDACRPvV5X0fpjKOZ6vNqXibYy4Vy1gKu/pVIc/f1osrL2/MH2xR7UebUZM\r\nbip8jGwqubgvpiVogNA6ACt3iVRQg7S4/XCCzU4hN/ZPK04JkF7dIRPvBOjMGDrY\r\nVCm9stu8KrWC9dbcuY94QRowePiOIcjjtKCOE6ErfhEJE1fp7qimEX9GGMsmzHnu\r\nwZtbnw1GeRCMrCQ5Jq8Xc79dOwq6auNqUTSITG8mD5b/nk6Ogvnn/pNXmxFEroC5\r\nV4AdXNw1BvOhJLM85p1SN6zxn0Wb7KTWVfZmzKJEp7nAPZ1UJFKiWNIdLpVed6xH\r\nHwIDAQAB\r\n-----END PUBLIC KEY-----\r\n","40-46;200-205;494-500"];
$ReadFunctions = [["all","Reads all sectors table"],["id","Read all that matches id in sectors"],["sectorsName","Read all that matches sectorsName in sectors"],["moreUsed","Read all that matches moreUsed in sectors"]];
$read = ["all","id","sectorsName","moreUsed"];
$columnas = [[" 1 unique id for each sector","id","INT","autoincremental "],["Sectors being offered (gastronomics, cloth, etc)","sectorsName","VARCHAR",""],["How many times where used (for statistics)","moreUsed","INT",""]];
$get = [["all","","Read all sectors",""],["","id","Read sectors by id.",""],["","sectorsName","Read sectors by sectorsName.",""],["","moreUsed","Read sectors by moreUsed.",""]];
$DBPASSWD = "DBPASSWD";
$source = "./sectors";
$auths = [];
$UpdateFunctions = [["all","id"],["sectorsName","id"],["moreUsed","id"],["moreUsed","sectorsName"]];
$update = [["all","id"],["sectorsName","id"],["moreUsed","id"],["moreUsed","sectorsName"]];
$WriteFunctions = [["setAll","id,sectorsName"]];
$nombreDeLaTabla = "sectors";
?>